In [1]:
#import dependencies
import pandas as pd
import gmaps
import requests
#import API key
from config import google_key

In [2]:
city_data_df=pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City ID,City,Country,Date,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Nuuk,GL,2021-12-17 05:01:46,64.1835,-51.7216,0.05,86,47,6.42
1,1,Port Alfred,ZA,2021-12-17 05:11:11,-33.5906,26.8910,61.86,49,62,9.24
2,2,Tigzirt,DZ,2021-12-17 05:11:12,36.8886,4.1198,51.62,58,0,7.23
3,3,Provideniya,RU,2021-12-17 05:11:12,64.3833,-173.3000,9.63,97,99,2.80
4,4,Chuy,UY,2021-12-17 05:11:12,-33.6971,-53.4616,64.69,79,44,9.71

In [3]:
# get data types
city_data_df.dtypes

City ID         int64
City           object
Country        object
Date           object
Latitude      float64
Longitude     float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# configure gmaps to using google API key
gmaps.configure(api_key=google_key)

In [5]:
# 1. Assign locations to lat, long pairs
locations=city_data_df[["Latitude","Longitude"]]

# 2. Assign weights variable to some value
max_temp=city_data_df["Max Temp"]

# 3. Assign figure variable to gmaps.figure() attribute
fig=gmaps.figure(center=(30.0,31.0), zoom_level=1.5)

# 4. Assign heatmap_layer variable to #3 and add it in
heat_layer=gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

# 5. Add heatmap layer
fig.add_layer(heat_layer)

# 6. Call figure to plot
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Heatmap for humidity
# 1. Assign locations to lat, long pairs
locations=city_data_df[["Latitude","Longitude"]]

# 2. Assign weights variable to some value
humidity=city_data_df["Humidity"]

# 3. Assign figure variable to gmaps.figure() attribute
fig=gmaps.figure(center=(30.0,31.0), zoom_level=1.5)

# 4. Assign heatmap_layer variable to #3 and add it in
heat_layer=gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

# 6. Call figure to plot
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
#heatmap for cloudiness

# 1. Assign locations to lat, long pairs
locations=city_data_df[["Latitude","Longitude"]]

# 2. Assign weights variable to some value
cloudiness=city_data_df["Cloudiness"]

# 3. Assign figure variable to gmaps.figure() attribute
fig=gmaps.figure(center=(30.0,31.0), zoom_level=1.5)

# 4. Assign heatmap_layer variable to #3 and add it in
heat_layer=gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False, max_intensity=300, point_radius=4)

# 6. Call figure to plot
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
#heat map for windspeed
# 1. Assign locations to lat, long pairs
locations=city_data_df[["Latitude","Longitude"]]

# 2. Assign weights variable to some value
wind_speed=city_data_df["Wind Speed"]

# 3. Assign figure variable to gmaps.figure() attribute
fig=gmaps.figure(center=(30.0,31.0), zoom_level=1.5)

# 4. Assign heatmap_layer variable to #3 and add it in
heat_layer=gmaps.heatmap_layer(locations, weights=wind_speed, dissipating=False, max_intensity=300, point_radius=4)

# 6. Call figure to plot
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
#ask customer to add min/max temp
min_temp=float(input("What is the minimum temperature you would like for your trip? "))
max_temp=float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [10]:
#Filter data to find cities in that range
preferred_cities_df=city_data_df.loc[(city_data_df["Max Temp"]<=max_temp) & (city_data_df["Max Temp"]>=min_temp)]
preferred_cities_df.head(10)

,City ID,City,Country,Date,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed
5,5,Bengkulu,ID,2021-12-17 05:11:13,-3.8004,102.2655,76.39,92,100,1.88
9,9,Saint-Pierre,RE,2021-12-17 05:11:14,-21.3393,55.4781,79.29,74,0,12.66
13,13,Atuona,PF,2021-12-17 05:06:47,-9.8000,-139.0333,78.15,71,23,12.28
16,16,Pho Chai,TH,2021-12-17 05:11:16,16.3283,103.7703,88.09,46,40,16.64
17,17,Souillac,MU,2021-12-17 05:11:16,-20.5167,57.5167,83.35,64,13,9.51
21,21,Rikitea,PF,2021-12-17 05:11:18,-23.1203,-134.9692,75.51,74,85,19.30
24,24,Butaritari,KI,2021-12-17 05:06:50,3.0707,172.7902,82.22,76,73,10.63
27,27,Hithadhoo,MV,2021-12-17 05:11:20,-0.6000,73.0833,81.99,73,73,4.27
30,30,Bodden Town,KY,2021-12-17 05:07:01,19.2833,-81.2500,76.93,94,40,5.75
34,34,Vaini,TO,2021-12-17 05:11:23,-21.2000,-175.2000,84.36,79,20,9.22

In [11]:
preferred_cities_df.count()

City ID       113
City          113
Country       113
Date          113
Latitude      113
Longitude     113
Max Temp      113
Humidity      113
Cloudiness    113
Wind Speed    113
dtype: int64

In [12]:
clean_cities_df=preferred_cities_df.dropna()

In [13]:
# create a dataframeto store hotel names along with city and country
hotel_df=clean_cities_df[["City", "Country", "Max Temp", "Latitude", "Longitude"]].copy()
hotel_df["Hotel Name"]=""
hotel_df.head(10)

            City Country  Max Temp  Latitude  Longitude Hotel Name
5       Bengkulu      ID     76.39   -3.8004   102.2655
9   Saint-Pierre      RE     79.29  -21.3393    55.4781
13        Atuona      PF     78.15   -9.8000  -139.0333
16      Pho Chai      TH     88.09   16.3283   103.7703
17      Souillac      MU     83.35  -20.5167    57.5167
21       Rikitea      PF     75.51  -23.1203  -134.9692
24    Butaritari      KI     82.22    3.0707   172.7902
27     Hithadhoo      MV     81.99   -0.6000    73.0833
30   Bodden Town      KY     76.93   19.2833   -81.2500
34         Vaini      TO     84.36  -21.2000  -175.2000

In [14]:
params={"radius":5000, "type":"lodging","key":google_key}

In [15]:
#iterate through df
for index, row in hotel_df.iterrows():
    lat=row["Latitude"]
    long=row["Longitude"]
    
    #add to params dictionary
    params["location"]= f"{lat},{long}"
    
    base_url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    #make a request and get JSON data from search
    hotels=requests.get(base_url, params=params).json()
    
    #grab first hotel from results and store name
    try:
        hotel_df.loc[index,"Hotel Name"]=hotels["results"][0]["name"]
    except(IndexError):
        print("Hotel not found...skipping")
hotel_df.head(10)

Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping

,City,Country,Max Temp,Latitude,Longitude,Hotel Name
5,Bengkulu,ID,76.39,-3.8004,102.2655,Grage Hotel Bengkulu
9,Saint-Pierre,RE,79.29,-21.3393,55.4781,Lindsey Hôtel
13,Atuona,PF,78.15,-9.8000,-139.0333,Villa Enata
16,Pho Chai,TH,88.09,16.3283,103.7703,ก๊อฟคุงยางมือสอง
17,Souillac,MU,83.35,-20.5167,57.5167,Shanti Maurice Resort & Spa
21,Rikitea,PF,75.51,-23.1203,-134.9692,People ThankYou
24,Butaritari,KI,82.22,3.0707,172.7902,Isles Sunset Lodge
27,Hithadhoo,MV,81.99,-0.6000,73.0833,Scoop Guest House
30,Bodden Town,KY,76.93,19.2833,-81.2500,Will T Place
34,Vaini,TO,84.36,-21.2000,-175.2000,Keleti Beach Resort

In [16]:
clean_hotel_df=hotel_df.dropna()

In [17]:
# add info template box
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

#store dataframe row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [18]:
# heat map for vacation spots

# 1. Assign locations to lat, long pairs
locations=city_data_df[["Latitude","Longitude"]]

# 2. Assign weights variable to some value
max_temp=city_data_df["Max Temp"]

# 3. Assign figure variable to gmaps.figure() attribute
fig=gmaps.figure(center=(30.0,31.0), zoom_level=1.5)

# 4. Assign heatmap_layer variable to #3 and add it in
heat_layer=gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)

# 5. Add heatmap layer
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 6. Call figure to plot
fig

IndexError: list index out of range